#
# WARNING: Do not edit this file.
# It was generated by processing {{ yadm.source }}
#

# Active python venv
activate() {
    if [[ ! -d .venv ]]; then
        echo "No virtualenv!"
        return 1
    fi
    . .venv/bin/activate || . .venv/Scripts/activate
}

# clear
alias c="clear"

# clean directory
alias cleanup="/bin/rm -f *# *~"

# Directories
alias home="cd ~"
alias root="cd /"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias .......="cd ../../../../../.."
alias ........="cd ../../../../../../.."
alias .........="cd ../../../../../../../.."
alias ..........="cd ../../../../../../../../.."
alias ...........="cd ../../../../../../../../../.."
alias ............="cd ../../../../../../../../../../.."
alias .............="cd ../../../../../../../../../../../.."

# ls/tree
alias ll="ls -lh"
alias la="ls -Alh"
alias trea="tree -a"
alias sl="sl -ad5w"

# Condor
alias cq="condor_q"

# CPU temp
cputemp() {
    paste <(cat /sys/class/thermal/thermal_zone*/type) <(cat /sys/class/thermal/thermal_zone*/temp) | column -s $'\t' -t | sed 's/\(.\)..$/.\1°C/'
}

# Poetry list outdated packages
poetry-outdated() {
    poetry show --outdated | grep --file=<(poetry show --tree | grep '^\w' | cut -d' ' -f1)
}

# color aliases (may already exist, but ¯\_(ツ)_/¯)
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Command replacements
which bat > /dev/null 2>&1 && alias cat="bat"
which rg  > /dev/null 2>&1 && alias grep="rg"

if which batcat > /dev/null 2>&1; then # bat named batcat on ubuntu
    alias bat=batcat
    alias cat=batcat
fi

{% if yadm.os == "WSL" %}

# https://github.com/microsoft/WSL/issues/4401#issuecomment-670080585
# function to check if in a windows of WSL dir
__is-windows-dir() {
    case "$PWD/" in
    /mnt/*)
        return $(true)
        ;;
    *)
        return $(false)
        ;;
    esac
}

{% else %}

# Dummy function that returns true on MSys2 and false otherwise
__is-windows-dir() {
    return $([[ "$(uname -o)" == "Msys" ]])
}

{% endif %}

git() {
    # Determine git executable for speedup in WSL
    if __is-windows-dir; then
        exe="git.exe"
    else
        exe="git"
    fi

    command $exe $@
}

ipy() {
    # Like the git but for ipython
    if __is-windows-dir; then
        exe="ipython.exe"
    else
        exe="ipython"
    fi

    command $exe $@
}

#
# apt
#
apt() {
    ## check if is sudoer
    if ! $(sudo -l &>/dev/null); then
        echo 'ERROR: root privileges are needed to run apt!'
        return 1
    fi

    cmd=$1
    shift

    case $cmd in
    ac)
        command sudo apt autoclean $@
        ;;
    autorm)
        command sudo apt autoremove $@
        ;;
    c)
        command sudo apt clean $@
        ;;
    i)
        command sudo apt install $@
        ;;
    rm)
        command sudo apt remove $@
        ;;
    up)
        command sudo apt update $@
        ;;
    upg)
        command sudo apt upgrade $@
        ;;
    *)
        command apt $cmd $@
        ;;
    esac
}
