#!/usr/bin/env sh
# -*- mode: shell-script -*-

# WARNING: Do not edit this file.
# It was generated by processing {{ yadm.source }}

echo "Installing starship!"

{% if yadm.os == "Msys" %}

# Download executable to ~/bin
mkdir -p ~/bin

starship_zip_download_url=$(
    curl -sL https://api.github.com/repos/starship/starship/releases/latest |
        jq -r ".assets[].browser_download_url" |
        grep "starship-x86_64-pc-windows-msvc.zip$"
)
curl -fsL "$starship_zip_download_url" -o ~/bin/starship.zip &&
    unzip ~/bin/starship.zip &&
    /bin/rm ~/bin/starship.zip

{% else %}

# Use starship installer
bash -c "$(curl -fsSL https://starship.rs/install.sh)"

{% endif %}
